import { ApplicationConfig, provideZoneChangeDetection, provideBrowserGlobalErrorListeners, importProvidersFrom } from '@angular/core';
import { provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';

import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth-interceptor';
import { 
  LucideAngularModule, 
  LayoutDashboard, 
  ShoppingCart, 
  Truck, 
  Factory, 
  Wheat, 
  Boxes, 
  Users, 
  FileText, 
  Tags, 
  Tractor, 
  CalendarDays, 
  ClipboardList, 
  Wrench, 
  Wallet, 
  BarChart3, 
  HardHat, 
  FileClock, 
  History, 
  Settings, 
  Leaf, 
  Menu, 
  Bell, 
  UserRound, 
  Plus,
  Minus,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Check,
  X,
  ArrowRightLeft,
  MapPin,
  Search,
  Volume2,
  Play,
  Square,
  Mic,
  MicOff,
  Warehouse,
  DollarSign,
  Calculator,
  AlertCircle,
  CheckCircle2,
  Clock,
  Package,
  Filter,
  Paperclip,
  ShieldCheck,
  UserCheck,
  LogOut,
  Eye,
  Lock,
  User,
  Zap,
  CreditCard,
  Printer,
  Receipt
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideHttpClient(withInterceptors([authInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({ 
        LayoutDashboard, 
        ShoppingCart, 
        Truck, 
        Factory, 
        Wheat, 
        Boxes, 
        Users, 
        FileText, 
        Tags, 
        Tractor, 
        CalendarDays, 
        ClipboardList, 
        Wrench, 
        Wallet, 
        BarChart3, 
        HardHat, 
        FileClock, 
        History, 
        Settings, 
        Leaf, 
        Menu, 
        Bell, 
        UserRound, 
        Plus,
        Minus,
        ChevronDown,
        ChevronRight,
        ChevronLeft,
        Check,
        X,
        ArrowRightLeft,
        MapPin,
        Search,
        Volume2,
        Play,
        Square,
        Mic,
        MicOff,
        Warehouse,
        DollarSign,
        Calculator,
        AlertCircle,
        CheckCircle2,
        Clock,
        Package,
        Filter,
        Paperclip,
        ShieldCheck,
        UserCheck,
        LogOut,
        Eye,
        Lock,
        User,
        Zap,
        CreditCard,
        Printer,
        Receipt
      })
    )
  ]
};
